### ISSUE TITLE
Issues with running.

### ISSUE THREAD

**Issue by MarkElf** [Krymonota/BungeeNCPNotify#7]
I've dropped in the .jar file and after booting up the server, I've run into this error. https://gyazo.com/b02e4b9334f5ecd81379cd8f8b139e14
Am I required to have the actually NCP.jar within the bungee plugins folder? 
Additionally, can you provide the permission node required to obtain these notifications? It's unclear on the page.

**Comment by Krymonota** [comment]
You have to put **BungeeNCPNotify.jar** and **NoCheatPlus.jar** into the _Bukkit/Spigot plugins folder_. If you put the plugin into the _BungeeCord plugins folder_, just move it. Otherwise I need the full stacktrace (error message).
You're right, the permissions are unclear on the page, I'll make sure to update it.
You need the permission **nocheatplus.notify** or **nocheat.admin** (see: https://github.com/NoCheatPlus/Docs/wiki/Permissions#miscellaneous-and-parent-permissions).

**Comment by MarkElf** [comment]
Thank you for taking the time to respond, however, I'd like to question as to how staff members receive notifications without the plugin inside the bungee folder, unless I've mis-read your response.

**Comment by Krymonota** [comment]
Well, I guess my answer wasn't that clear.

You dropped the plugin .jar file into the _BungeeCord plugins folder_, that's **wrong** (and also causing the error).
You have to put both plugins, BungeeNCPNotify and NoCheatPlus, into the **Spigot plugins folder**.

BungeeNCPNotify is a **Spigot plugin**, it just uses BungeeCord as a communication gateway to inform the other servers (about cheat violations) inside the BungeeCord network.
In this case, you don't need to install any BungeeCord plugins.

**Comment by Krymonota** [comment]
_BungeeNCPNotify_ sends the data using the **Bukkit & Bungee Plugin Messaging Channel** to all other servers inside the BungeeCord network.
If _BungeeNCPNotify_ is installed on these servers, they will process the data.
There's no need to add a plugin to BungeeCord - a Spigot plugin fulfills the job.
